### ISSUE TITLE
Where is the file "prepare.jl"?

### ISSUE THREAD

**Issue by lennyliu2000** [cvigilv/simspread#1]
The file "NetworkBasedInference.jl" in the trail "src/modules/NetworkBasedInference.jl/src/" contains a line of code which is "include("prepare.jl")". But there is no such file in that path. How can this problem be solved? Was the file not uploaded when the project was created in the first place?

**Comment by cvigilv** [comment]
@lennyliu2000 The modules folder was pushed unintentionally, since all the required scripts to reproduce the results are found in the src/predict folder.

Are you interested in reproducing the results? I can give you a hand if necesarry. Also, if you are aiming to work with SimSpread, we have developed a Julia package named (SimSpread.jl)[github.com/cvigilv/SimSpread.jl]

**Comment by lennyliu2000** [comment]
@cvigilv So I'm asking, inside the results folder is the full result of the code run right? If I want to reproduce the results, what help will you give me? Actually I would like to use the SDTNBI algorithm that you used for the performance comparison, but the SimSpread algorithm is also very interesting to me!

**Comment by cvigilv** [comment]
> So I'm asking, inside the results folder is the full result of the code run right?

Yes, the full results are available in the `results` folder and should result in the same results if you rerun the predictions.

> If I want to reproduce the results, what help will you give me? 

Any inquire regarding this results, please just leave me an issue here and I can give you a hand. I'm here to help in whatever you need.

> Actually I would like to use the SDTNBI algorithm that you used for the performance comparison, but the SimSpread algorithm is also very interesting to me!

If you are interested in running the SDTNBI algorithm, you can either (1) use the SDTNBI prediction scripts found [here](https://github.com/cvigilv/simspread/blob/1fa6d3151b7a2c2eb0bf695b5f22be983d81670a/src/predict/10fold/SDTNBI.kFold.jl#L39-L195)) or (2) you can use the SimSpread.jl package and skip the similarity featurization step (refer to [documentation](https://cvigilv.github.io/SimSpread.jl/stable/tutorial/getting-started/) for step by step instructions). I would recommend the later since its a much more recent and feature complete alternative and it can be adapted to whatever your problem is.
